language: python

python:
  - "3.6"
  - "3.7-dev"

install:
  - "pip install -r requirements-ci.txt"

script:
  # ignore output from install
  - python setup.py install >> /dev/null
  - snekchek

cache: pip

notifications:
  email: false
